export const SELECT_KEYBOARDCASE = 'SELECT_KEYBOARDCASE';
export const SELECT_KEYCAPSET = 'SELECT_KEYCAPSET';
export const SELECT_SWITCHES = 'SELECT_SWITCHES';
export const SELECT_STABILIZERS = 'SELECT_STABILIZERS';