export const SET_KEYBOARDCASE = 'SET_KEYBOARDCASE';
export const SELECT_KEYBOARDCASE = 'SELECT_KEYBOARDCASE';
export const REMOVE_SELECTED_KEYBOARDCASE = 'REMOVE_SELECTED_KEYBOARDCASE';
export const LOAD_KEYBOARDCASES = 'LOAD_KEYBOARDCASES';

export const SELECT_KEYCAPSET = 'SELECT_KEYCAPSET';
export const SELECT_SWITCHES = 'SELECT_SWITCHES';
export const SELECT_STABILIZERS = 'SELECT_STABILIZERS';

export const LOAD_KEYCAPSETS = 'LOAD_KEYCAPSETS';
export const SET_KEYCAPSET = 'SET_KEYCAPSET';
